# Generated by Django 3.2 on 2021-04-22 19:48

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowUserModel',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('nick_name', models.CharField(max_length=30)),
                ('avatar', models.ImageField(default='templates/deficon.png', upload_to='')),
                ('short_name', models.CharField(default='noname', max_length=120, unique=True)),
            ],
            options={
                'ordering': ['short_name'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='tech.lowusermodel')),
                ('follows', models.ManyToManyField(related_name='_tech_subscribers_follows_+', to='tech.Subscribers')),
            ],
        ),
        migrations.CreateModel(
            name='MomentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.lowusermodel')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
