# Generated by Django 3.2 on 2021-05-10 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentsmodel',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='commentsmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tech.lowusermodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='momemt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tech.momentmodel'),
        ),
        migrations.AlterField(
            model_name='commentsmodel',
            name='text',
            field=models.TextField(),
        ),
    ]
