# Generated by Django 3.2 on 2021-04-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lowusermodel',
            options={'ordering': ['nick_name']},
        ),
        migrations.AlterModelOptions(
            name='momentmodel',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='momentmodel',
            name='data',
        ),
        migrations.AddField(
            model_name='lowusermodel',
            name='short_name',
            field=models.CharField(default='noname', max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='momentmodel',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
