# Generated by Django 3.2 on 2021-05-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='TagModel',
        ),
    ]
