# Generated by Django 3.2 on 2021-05-04 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_lowusermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentmodel',
            name='likes',
            field=models.ManyToManyField(related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
