# Generated by Django 3.2 on 2021-05-07 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_rename_tag_tagmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowusermodel',
            name='avatar',
            field=models.ImageField(default='templates/deficon.png', upload_to='./templates/'),
        ),
        migrations.AlterField(
            model_name='momentmodel',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='MomentModel', to='tech.TagModel'),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tagmodel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
