# Generated by Django 3.2 on 2021-05-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0002_auto_20210510_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsmodel',
            old_name='momemt',
            new_name='moment',
        ),
    ]
