# Generated by Django 3.2 on 2021-05-04 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_momentmodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentmodel',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
