# Generated by Django 3.2 on 2021-05-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0003_auto_20210507_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
