# Generated by Django 3.2 on 2021-05-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0005_remove_momentmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='momentmodel',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='MomentModel', to='tech.TagModel'),
        ),
    ]
