# Generated by Django 3.2 on 2021-05-07 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0007_alter_momentmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentmodel',
            name='likes',
            field=models.ManyToManyField(default=None, null=True, related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='momentmodel',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, to='tech.TagModel'),
        ),
    ]
