# Generated by Django 3.2 on 2021-05-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0008_auto_20210507_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momentmodel',
            name='image',
            field=models.ImageField(upload_to='./templates/'),
        ),
    ]
