# Generated by Django 3.2 on 2021-05-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0009_alter_momentmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowusermodel',
            name='avatar',
            field=models.ImageField(default='templates/deficon.png', upload_to='templates/'),
        ),
        migrations.AlterField(
            model_name='momentmodel',
            name='image',
            field=models.ImageField(upload_to='templates/'),
        ),
    ]
