# Generated by Django 3.2 on 2021-05-07 21:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0010_auto_20210507_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowusermodel',
            name='avatar',
            field=models.ImageField(default='templates/deficon.png', upload_to='nginx/'),
        ),
        migrations.AlterField(
            model_name='momentmodel',
            name='likes',
            field=models.ManyToManyField(default=None, related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='momentmodel',
            name='tags',
            field=models.ManyToManyField(default=None, to='tech.TagModel'),
        ),
    ]
