# Generated by Django 3.2 on 2021-05-07 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tech', '0011_auto_20210507_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1200)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('follows', models.ManyToManyField(related_name='_tech_subscribersmodel_follows_+', to='tech.SubscribersModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='follows',
        ),
        migrations.AlterField(
            model_name='momentmodel',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='MomentModel_tags', to='tech.TagModel'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='momemt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech.momentmodel'),
        ),
        migrations.AddField(
            model_name='commentsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
